services:
  - type: web
    name: backend-fastapi
    env: python
    plan: free
    region: frankfurt
    branch: main
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host=0.0.0.0 --port=10000"
    autoDeploy: true
